version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=aida
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  python: &python
    build:
      context: .
      dockerfile: docker/dev/python/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    volumes:
      - ./code:/code
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - rabbit
      - celery
  rabbit:
    image: rabbitmq:3.7-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=aida
      - RABBITMQ_DEFAULT_PASS=aida
    ports:
        - "5672:5672"
  celery:
    <<: *python
    command:  celery -A cinema  worker -l info
    depends_on:
        - rabbit
        - db
