# Generated by Django 2.0.12 on 2020-05-22 13:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_to', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CommentLike',
                'verbose_name_plural': 'CommentLikes',
            },
            managers=[
                ('likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2550)),
                ('price', models.IntegerField(default=1000)),
                ('sum_of_rates', models.IntegerField(default=0)),
                ('no_of_rates', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('premiere', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 13, 8, 6, 492155, tzinfo=utc))),
                ('country', models.CharField(default='Kazakhstan', max_length=255)),
                ('genre', models.CharField(default='Fantasy', max_length=255)),
                ('movie_logo', models.CharField(default='', max_length=255)),
                ('directed_by', models.CharField(default='Alikhan', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=utils.upload.image_path, validators=[utils.validators.image_size, utils.validators.image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'MovieLike',
                'verbose_name_plural': 'MovieLikes',
            },
            managers=[
                ('likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Myrating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
            ],
        ),
    ]
