# Generated by Django 3.0.5 on 2020-04-01 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191222_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directed_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 4, 1)),
        ),
    ]
