# Generated by Django 3.0.5 on 2020-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200401_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_logo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directed_by',
            field=models.CharField(max_length=255),
        ),
    ]
