# Generated by Django 3.0.5 on 2020-04-01 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200401_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='Kazakhstan', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directed_by',
            field=models.CharField(default='Alikhan', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Fantasy', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 1, 17, 6, 51, 319695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
