# Generated by Django 3.0.5 on 2020-04-02 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200401_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 2, 10, 39, 8, 418287, tzinfo=utc)),
        ),
    ]
